---
language: python
services: docker

env:
  global:
    - IMAGE_NAME: coglinev3/alpine
  matrix:
    - IMAGE_TAG: alpine-3.9-bash.yml
    - IMAGE_TAG: alpine-3.10-bash.yml
    - IMAGE_TAG: alpine-3.11-bash.yml

install:
  # Upgrade Docker and Python
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Steps befor running tests
  # - >
  #   sudo mkdir -p /etc/ansible
  #   && sudo bash -c 'echo -e "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts'

script:
  # Build Alpine image
  - ansible-playbook alpine-${IMAGE_TAG}.yml
  # Verify Bash is available in the container
  - docker run -it  ${IMAGE_NAME}:${IMAGE_TAG} env TERM=xterm bash --version
