---
version: ~> 1.0
language: python
services: docker

env:
  global:
    - PROJECT_NAME: container-alpine
  matrix:
    - PLAYBOOK: alpine-3.9-bash.yml
    - PLAYBOOK: alpine-3.10-bash.yml
    - PLAYBOOK: alpine-3.11-bash.yml

install:
  - cat /etc/os-release
  # Upgrade Docker and Python
  - sudo apt-get update
  - >
    sudo apt-get -y -o Dpkg::Options::="--force-confnew" install
    docker-ce
    libssl-dev
    libffi-dev
    python3
    python3-pip
    python3-setuptools
    python3-software-properties
    python3-wheel
    sudo
  # Install test dependencies.
  - pip3 install ansible docker

before_script:
  # Steps befor running tests
  # - cd ../

script:
  # Run tests.
  - ansible-playbook ${PLAYBOOK} -i hosts
