---
language: python
services: docker

env:
  global:
    - PROJECT_NAME: container-alpine
  matrix:
    - PLAYBOOK: alpine-3.9-bash.yml
    - PLAYBOOK: alpine-3.10-bash.yml
    - PLAYBOOK: alpine-3.11-bash.yml

install:
  # Upgrade Docker and Python
  - pip install molecule yamllint ansible-lint docker

before_script:
  # Steps befor running tests
  - >
    sudo mkdir -p /etc/ansible
    && sudo bash -c 'echo -e "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts'

script:
  # Run tests.
  - ansible-playbook ${PLAYBOOK}
