---
dist: focal
addons:
  apt:
    packages:
    - libssl-dev
    - libffi-dev
    - python3
    - python3-pip
    - python3-setuptools
    - python3-software-properties
    - python3-wheel

language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAMESPACE: coglinev3
    - IMAGE_NAME: alpine
    - ALPINE_MAJOR_VERSION: 3
  matrix:
    - ALPINE_MINOR_VERSION: 12
      IMAGE_ALTERNATE_TAG: latest
    - ALPINE_MINOR_VERSION: 11
    - ALPINE_MINOR_VERSION: 10
    - ALPINE_MINOR_VERSION: 9

install:
  # Install Ansible and Python Docker Module
  - pip3 install ansible docker

before_script:
  # Configure Ansible
  - cp .travis/ansible.cfg ~/.ansible.cfg
  - mkdir -p ~/.ansible && cp .travis/hosts ~/.ansible
  # Show Ansible version
  - ansible --version

script:
  # Build Docker image
  - ansible-playbook container-alpine.yml

after_success:
  - >
    echo Start a container from image
    ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${ALPINE_MAJOR_VERSION}.${ALPINE_MINOR_VERSION}
    && cid=$(docker run -d --rm --name check_python
    ${IMAGE_NAMESPACE}/${IMAGE_NAME}:${ALPINE_MAJOR_VERSION}.${ALPINE_MINOR_VERSION}
    tail -f /dev/null)
  # show container os-release
  - docker exec ${cid} env TERM=xterm cat /etc/os-release
  # Verify Bash is available in the container
  - docker exec ${cid} env TERM=xterm bash --version
  # Stop the container
  - docker stop ${cid}

deploy:
  provider: script
  script: bash scripts/docker_push
  cleanup: false
  on:
    branch: master

jobs:
  include:
    - stage: trigger container-python
      if: branch = master
      install: skip
      before_script: skip
      after_success: skip
      deploy: skip
      script: bash .travis/trigger-job $(dirname $TRAVIS_REPO_SLUG) container-python
