---
language: python
services: docker

env:
  global:
    - IMAGE_NAME: coglinev3/alpine
  matrix:
    - IMAGE_TAG: 3.9-bash
    - IMAGE_TAG: 3.10-bash
    - IMAGE_TAG: 3.11-bash

install:
  # Upgrade Docker and Python
  - pip install molecule docker

script:
  # Build Alpine image
  - ansible-playbook alpine-${IMAGE_TAG}.yml

  # Verify Bash is available in the container
  - docker run -it  ${IMAGE_NAME}:${IMAGE_TAG} env TERM=xterm cat /etc/os-release

  # Verify Bash is available in the container
  - docker run -it  ${IMAGE_NAME}:${IMAGE_TAG} env TERM=xterm bash --version
