---
dist: bionic
addons:
  apt:
    packages:
    - docker-ce
    - libssl-dev
    - libffi-dev
    - python3
    - python3-pip
    - python3-setuptools
    - python3-software-properties
    - python3-wheel

language: minimal

services:
  - docker

env:
  global:
    - IMAGE_NAME: coglinev3/alpine
  matrix:
    - IMAGE_TAG: 3.11-bash
      IMAGE_ALTERNATE_TAG: latest
    - IMAGE_TAG: 3.10-bash
    - IMAGE_TAG: 3.9-bash

install:
  # Install Ansible and Python Docker Module
  - pip3 install ansible docker

before_script:
  # Configure Ansible
  - cp .travis/ansible.cfg ~/.ansible.cfg
  - mkdir -p ~/.ansible && cp .travis/hosts ~/.ansible
  # Show Ansible version
  - ansible --version

script:
  # Build Docker image
  - ansible-playbook alpine-${IMAGE_TAG}.yml

after_success:
  # Verify container OS release
  - docker run -it --rm ${IMAGE_NAME}:${IMAGE_TAG} env TERM=xterm cat /etc/os-release

  # Verify Bash is available in the container
  - docker run -it --rm ${IMAGE_NAME}:${IMAGE_TAG} env TERM=xterm bash --version

deploy:
  provider: script
  script: bash scripts/docker_push
  cleanup: false
  on:
    branch: master
