---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    base_image: alpine
    base_image_tag: "3.10"
    container_name: alpine_310_bash
    image_namespace: coglinev3
    image_name: alpine
    image_tag: 3.10-bash
  pre_tasks:
    - debug:
        msg: 'image: {{ base_image }}:{{ base_image_tag }}'
    - name: Make the latest version of the base image available locally.
      docker_image:
        name: '{{ base_image }}:{{ base_image_tag }}'
        source: pull
        force_source: true
    - name: Create the Docker container.
      docker_container:
        image: '{{ base_image }}:{{ base_image_tag }}'
        name: '{{ container_name }}'
        command: sleep 1h
    - name: Add the newly created container to the inventory.
      add_host:
        hostname: '{{ container_name }}'
        ansible_connection: docker
  tasks:
    - name: "Install Bash"
      # raw: apk update && apk add --no-cache bash
      raw: apk add --update-cache bash && rm -rf /var/cache/apk/*
      delegate_to: '{{ container_name }}'
  post_tasks:
    - name: Commit the container.
      command: >
        docker commit
        --author "Cogline.v3"
        {{ container_name }} {{ image_namespace }}/{{ image_name }}:{{ image_tag }}
    - name: Remove the container.
      docker_container:
        name: '{{ container_name }}'
        state: absent
