---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    alpine_major_version: "{{ lookup('env','ALPINE_MAJOR_VERSION') | default('3', true) }}"
    alpine_minor_version: "{{ lookup('env','ALPINE_MINOR_VERSION') | default('13', true) }}"
    base_image: alpine
    base_image_tag: "{{ alpine_major_version }}.{{ alpine_minor_version }}"
    container_name: "alpine_{{ alpine_major_version }}{{ alpine_minor_version }}_bash"
    image_namespace: coglinev3
    image_name: alpine
    image_tag: "{{ alpine_major_version }}.{{ alpine_minor_version }}"
  pre_tasks:
    - name: Make the latest version of the base image available locally.
      docker_image:
        name: '{{ base_image }}:{{ base_image_tag }}'
        source: pull
        force_source: true
    - name: Create the Docker container.
      docker_container:
        image: '{{ base_image }}:{{ base_image_tag }}'
        name: '{{ container_name }}'
        container_default_behavior: no_defaults
        command: sleep 1h
    - name: Add the newly created container to the inventory.
      add_host:
        hostname: '{{ container_name }}'
        ansible_connection: docker
  tasks:
    - name: "Install Bash"
      raw: apk add --update-cache bash && rm -rf /var/cache/apk/*
      delegate_to: '{{ container_name }}'
  post_tasks:
    - name: Commit the container.
      command: >
        docker commit
        --author "Cogline.v3"
        {{ container_name }} {{ image_namespace }}/{{ image_name }}:{{ image_tag }}
    - name: Remove the container.
      docker_container:
        name: '{{ container_name }}'
        state: absent
        container_default_behavior: no_defaults
