---
- hosts: localhost
  connection: local
  gather_facts: "no"
  vars:
    alpine_version: "{{ lookup('env','ALPINE_VERSION') | default('3.15', true) }}"
    base_image: alpine
    container_name: "alpine_bash"
    image_namespace: coglinev3
    image_name: alpine
  pre_tasks:
    - name: Make the latest version of the base image available locally.
      docker_image:
        name: '{{ base_image }}:{{ alpine_version }}'
        source: pull
        force_source: true
    - name: Create the Docker container.
      docker_container:
        image: '{{ base_image }}:{{ alpine_version }}'
        name: '{{ container_name }}'
        container_default_behavior: no_defaults
        command: sleep 1h
    - name: Add the newly created container to the inventory.
      add_host:
        hostname: '{{ container_name }}'
        ansible_connection: docker
  tasks:
    - name: "Install Bash"
      raw: apk add --update-cache bash && rm -rf /var/cache/apk/*
      delegate_to: '{{ container_name }}'
  post_tasks:
    - name: Commit the container.
      command: >
        docker commit
        --author "Cogline.v3"
        {{ container_name }} {{ image_namespace }}/{{ image_name }}:{{ alpine_version }}
    - name: Remove the container.
      docker_container:
        name: '{{ container_name }}'
        state: absent
        container_default_behavior: no_defaults
